name: AutoRecord
on:
  workflow_dispatch:
  schedule:
    - cron: '30 00 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup
        uses: actions/setup-python@v4
        with:
            python-version: "3.10"
      - name: Install
        run:
          pip install -r requirements.txt
      - name: Debug
        run: |
          echo "MAIL=${{ secrets.MAIL }}"
          echo "PWD=${{ secrets.PWD }}"
      - name: Run
        env:
            URL: ${{secrets.URL}}
            MAIL: ${{ secrets.MAIL }}
            PWD: ${{ secrets.PWD }}
        run: |
          python main.py
      - name: git config
        run: |-
          git config --global user.name "Github Actions"
          git config --global user.email "actions@gmail.com"
      - name: Push
        run: |-
          git diff
          git add -A
          git commit -m "update by github actions"
          git push
